name: Release Binaries for chaos-game

on:
  release:
    types: [published]

jobs:
  build-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release --locked

      - name: Package for release
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a -tzip chaos-game-${{ github.ref_name }}-${{ runner.os }}.zip ./target/release/chaos-game.exe
          else
            tar -czvf chaos-game-${{ github.ref_name }}-${{ runner.os }}.tar.gz -C ./target/release/ chaos-game
          fi
        shell: bash

      - name: Upload Release Asset
        # This uses the full commit hash for version v4.0.2 to avoid tag resolution issues.
        uses: actions/upload-release-asset@18da4306385d32152a3254331d044f54e1b782c5
        with:
          asset_path: chaos-game-${{ github.ref_name }}-${{ runner.os }}.*
          asset_name: chaos-game-${{ github.ref_name }}-${{ runner.os }}.${{ runner.os == 'Windows' && 'zip' || 'tar.gz' }}
          asset_content_type: application/octet-stream